version: '3.8'

services:
  gtb-postgres:
    image: postgres:15-alpine
    container_name: gtb-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - gtb-db-data:/var/lib/postgresql/data

volumes:
  gtb-db-data:
